MetricsApp - Cryptoview
Ochiengsteven/metrics-app pull request #6
Opened 2023-09-06 13:37 UTC by Ochiengsteven

🚀 **Feature Implementation: Fulfillment of All Project Requirements**

This pull request represents a significant milestone in the development of my project. I've successfully implemented all of the specified project requirements, covering design, interactions, testing, technical aspects, and documentation.

**Achievements:**

✅ Implemented API Integration: I've seamlessly integrated the selected crpto-data API, fetching numeric values based on the provided parameters.

✅ Stylish Design: My web application boasts an aesthetically pleasing design, following the design guidelines meticulously. 

✅ Seamless Interactions: Users can effortlessly navigate the home and details pages, exploring categories and accessing detailed data.

✅ Testing Excellence: I've thoroughly tested our application, covering both unit tests for Redux code and integration tests using React Testing Library. 

✅ Redux at Its Best: The Redux store elegantly stores and manages data retrieved from the API. I've employed a Filter stateless component to enhance data presentation.

✅ Robust Routing: My single-page application features unique routes for every page, ensuring a smooth user experience.

✅ Comprehensive Documentation: I've documented my project, following the guidelines provided. The README includes essential information about design, interactions, testing, and technical details.

✅ Video Presentation: To offer an in-depth look at my project, I've recorded a video presentation covering its features, demo, and highlighting notable pieces of code.

> As I've met all the project requirements and delivered a robust application. I'm excited about the progress I've made and looks forward to your feedback and suggestions.

🙌 Please review  this pull request to the `dev` branch.

2023-09-06 14:15 UTC, DammyShittu requested changes
Hi @Ochiengsteven,

## Highlights
✔️ Passing tests
✔️ Unique route

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 14:15 UTC, DammyShittu commented on README.md
> +- You can find the website [here](https://ochiengsteven.github.io/metrics-app/)
- [ ] Nothing is displayed when I visit your live demo link. I suggest you look into that.

  ![image](https://github.com/Ochiengsteven/metrics-app/assets/54848363/5ab0a11f-ea1d-4162-96f2-d556a6d9c5ca)

2023-09-06 14:15 UTC, DammyShittu commented on README.md
> +This is the [Video](https://www.loom.com/share/5c93582556234a94a153c825c5d91f78?sid=4b15cc68-3d06-4026-84e6-dca7cd792b68) walk through the project.
- [ ] Perhaps it is an issue with your mic but your video walkthrough is not audible enough, and I could not hear what you were saying. Kindly re-record your video presentation and ensure it is audible enough so viewers don't have to strain their ears to hear your presentation. Being loud and clear in presentations would be big bonus in future career-related projects

2023-09-06 14:15 UTC, DammyShittu commented on package.json
> +  "homepage": "http://Ochiengsteven.github.io/metrics-app",
- [ ] When I start up your app it opens on a route that does not exist and so displays nothing. This could be why your live demo link is not working. Kindly ensure that when the app is started it starts on the root path. When I remove `/metrics-app` it fixes the problem. You may want to look at that.

  ![image](https://github.com/Ochiengsteven/metrics-app/assets/54848363/062878a0-50ec-44ff-9cf7-9a409ee66303)

2023-09-06 14:15 UTC, DammyShittu commented on src/components/CryptoDetails.js
> +    </div>
- [ ] The data on all the detail pages are the same as if this is a dummy app. No matter the exchange and pair I select from the homepage the exchange is always the same BinanceFuture, with the same price and volume. Kindly ensure you display dynamic content depending on the selection.

- [ ] All your details routes are also the same `/crypto/undefined`. Kindly ensure the routes are unique, like `/crypto/:uuid`

  ![image](https://github.com/Ochiengsteven/metrics-app/assets/54848363/d8d26141-6a80-4ae3-9705-83cceb1e1fe3)

2023-09-07 11:14 UTC, Ochiengsteven commented
Hi @DammyShittu I've made all the above corrections and submitted for review. Thank you for your review.

2023-09-07 11:26 UTC, DammyShittu approved these changes
Hi @Ochiengsteven,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 11:53 UTC, merged